cook/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls.static import static

from cook import views


urlpatterns = patterns(
    '',
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name="detail")
)

cookbook/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cookbook.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('cook.urls', namespace='cook')),
    url(r'^admin/', include(admin.site.urls)),
)

cook/models.py
from django.db import models


class ActionClusterType(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class ActionCluster(models.Model):
    type = models.ForeignKey(ActionClusterType)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    ingredients = models.ManyToManyField("IngredientCluster", null=True, blank=True)
    parents = models.ManyToManyField("self", null=True, blank=True)

    def __str__(self):
        return self.name


class IngredientClusterType(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class IngredientCluster(models.Model):
    type = models.ForeignKey(IngredientClusterType)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000)
    actions = models.ManyToManyField(ActionCluster, null=True, blank=True)
    parents = models.ManyToManyField("self", null=True, blank=True)

    def has_actions(self):
        return self.actions.count() > 0

    def __str__(self):
        return self.name

cook/views.py
from django.shortcuts import render
from django.views import generic

from cook.models import ActionCluster, IngredientCluster


class DetailView(generic.DetailView):
    model = IngredientCluster
    template_name = "cook/detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        flat = []
        queue = [context["ingredientcluster"]]
        while len(queue) > 0:
            i = queue[0]
            for action in i.actions.all():
                flat.append((action, i))
                for ingredient in action.ingredients.all():
                    queue.append(ingredient)
            queue.pop(0)
        context["flat_actions"] = reversed(flat)
        return context

cook/templates/cook/detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {% load bootstrap3 %}
    {% bootstrap_css %}
</head>
<body>
    <div class="container-fluid">
        <h1>{{ ingredientcluster.name }}</h1>
        {% for action in flat_actions %}
            <div class="panel panel-info">
                <div class="panel-heading">
                    {{ action.0 }} -> {{ action.1 }}
                </div>
                <div class="panel-body"
                {% for parent in action.0.parents.all %}
                    <h5>{{ parent }} {{ parent.type }} {{ parent.type.description }}</h5>
                {% endfor %}
                {% for ingredient in action.0.ingredients.all %}
                    <div>
                        <a href="{% url 'cook:detail' ingredient.id %}">{{ ingredient }}</a>
                        {% for parent in ingredient.parents.all %}
                            <h5>{{ parent }} {{ paretn.type }} {{ parent.type.description }}</h5>
                        {% endfor %}
                    </div>
                {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

</body>
</html>